### ISSUE TITLE
Switch on Electron

### ISSUE THREAD

**Issue by IonicaBizau** [mapaiva/GitPie#13]
@mapaiva I remember we talked about this before, but I'm going to open the subject again. I'm sure if we switch on Electron we will get a bunch of stars just because of that. :smile:

Since it's built by GitHub and we're building something for Git, it's already a good business thing.

[Here](https://github.com/atom/electron/blob/master/docs/development/atom-shell-vs-node-webkit.md#technical-differences-between-electron-and-nwjs-formerly-node-webkit) you can see a comparison between the two platforms.

**Comment by mapaiva** [comment]
@IonicaBizau I've been thinking about Electron and I consider this a very nice feature. I didn't get deeper on `electron` like a said to you in the past, but I saw that it has native dialogs what is super cool. PS: I saw yours [eletronify](https://github.com/IonicaBizau/electronify) and I liked a lot :smile: 

It's a nice but big change. I belive that is better us stabilized in the version 0.1.0 with the latest features like `stash`.

After that, we can start the magic!! LOL

**Comment by IonicaBizau** [comment]
@mapaiva Haha, thanks for the :star: btw!

Maybe I can do it. I worked with both webkit and electron, but electron is way better from my perspective. At least is built by GitHub. :smile:

**Comment by mapaiva** [comment]
@IonicaBizau You're welcome rsrs

I belive that Electron have some features better than nw.js. Updater mostly haha. Develop a multiplataform updater is a very hard work, trust me kk.

**Comment by IonicaBizau** [comment]
> Develop a multiplataform updater is a very hard work, trust me kk.

@mapaiva They will be having the same problems we have, then. I guess they will build such a thing anyway, and we will enjoy and use it. :smile:

**Comment by mapaiva** [comment]
@IonicaBizau seriously?? hahaha
Ok we can do that :smile:

**Comment by mapaiva** [comment]
@IonicaBizau I will create a v0.2.0 branch and than create a electron branch. I think we can start the migration from nw.js to electron LOL. Have you ever create some Electron app? There are some patterns, guide lines?

**Comment by IonicaBizau** [comment]
@mapaiva I'm working on some Electron apps, but didn't open-source them yet. Electronify makes the life simple, so I would suggest to use it: https://github.com/IonicaBizau/electronify#example :smile:

**Comment by mapaiva** [comment]
Fixed by #22
