### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by IonicaBizau** [mapaiva/GitPie#14]
How is the versioning done?

Personally, I like more the `major.minor.patch` notation (like you already have in [`package.json`](https://github.com/mapaiva/GitPie/blob/9669e6f9dd38018ae30a6ca141a6ea13bb1ff240/package.json#L3)), but I see that in the releases page you prefixed everything with `v`.

Also, when I release initial releases I do `1.0.0`. How about here?

I'm not going to enforce my guidelines here, but of course, I can give a piece of advice, at least ask some questions. :grin:

**Comment by mapaiva** [comment]
I belive that a `major.minor.patch` structure works well and I do it with pie. I just put the v prefix for convention like on [linux](https://github.com/torvalds/linux) project.

>  Also, when I release initial releases I do 1.0.0. How about here? 

I belive that `1.0.0` is for when the project is stable and with a functional updater module. Until there, I like the ideia to keep the clearly impression that GitPie is under development. For example, the Atom editor still under 1.0.19 version and is pretty stable.

**Comment by IonicaBizau** [comment]
Got it! :+1:
