### ISSUE TITLE
How to start the app?

### ISSUE THREAD

**Issue by IonicaBizau** [mapaiva/GitPie#15]
So, I ran `grunt dev` and then how can I start the app?

**Comment by mapaiva** [comment]
The `grunt dev` task just convert alterations in `all.scss` into a `all.css` file.

You must first execute `grunt build`. It will create two folders `build` where the binaries for the 3 platforms will stay and `chache`. Inner chache, get in on `0.12.0` folder and next on the folder of your os. In my case is `linux64`. At this point just execute the `nw` program.

It will launch the node-webkit window. Just drag and drop the `index.html` file of the app inner the nw windows and voilá... GitPie is running and you can do any test you want. :smile:  rsrsrs

**Comment by IonicaBizau** [comment]
Ah, got it. :+1:

**Comment by IonicaBizau** [comment]
Thanks! :apple:

**Comment by mapaiva** [comment]
You're welcome XD
