### ISSUE TITLE
Use ES6

### ISSUE THREAD

**Issue by IonicaBizau** [mapaiva/GitPie#16]
Is it fine to write the code in ES6 format? At least that would work when we switch on Electron.

What do you think?

**Comment by mapaiva** [comment]
I think a great ideia. I made some tests with ES6 lately and I liked it a lot. Just two questions:
- Is electron works fine with ES6?
- Will we need a preprocessor like [babel](http://babeljs.io)?

I used babel with grunt in a module and works pretty good.

**Comment by IonicaBizau** [comment]
I think so. I only used ES6 in a server package, using Node 4.2.0, and `class`es and arrow functions work fine. Looks like `import` is not yet implemented.

I wouldn't vote for using a preprocessor but to use what the platform supports natively.

Electron is basically Node + Chromium–which should support ES6 features. :smile:

**Comment by mapaiva** [comment]
I belive that ES6 running natively is much more productive than a preprocessor too. kkk

If electron supports ES6 features I vote for we use it :D

**Comment by IonicaBizau** [comment]
:grin:
