### ISSUE TITLE
Tratativa de usuario global

### ISSUE THREAD

**Issue by lvlofenix** [mapaiva/GitPie#39]
Acabei de instalar o git e em seguida o gitpie e ao abrir o gitpie me foi apresentado a seguinte mensagem.

[Window Title]
GitPie

[Content]
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git config --global -l"
fatal: unable to read config file 'C:\Users\fenix/.gitconfig': No such file or directory

[OK]

como conversado isso é por causa do usuario global... teria como realizar uma tratativa?

**Comment by mapaiva** [comment]
A melhoria já foi realizada e estará disponível no proximo release.
Obrigado pelo report :smile:
