### ISSUE TITLE
Gulp Dev

### ISSUE THREAD

**Issue by rafaelstz** [mapaiva/GitPie#45]
Todas as tasks estão funcionando mas a `gulp dev` está com o seguinte erro:

![image](https://cloud.githubusercontent.com/assets/610598/15508624/99b8a346-21a6-11e6-8a12-dafb9a69cf29.png)

**Comment by mapaiva** [comment]
@rafaelstz Esse erro parece estar relacionado ao número de arquivos que estão sendo observados... Estranho que eu uso linux e não tenho esse problema :thought_balloon: De qualquer forma, estão ai duas possíveis soluções.

http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
https://github.com/gulpjs/gulp/issues/217

**Comment by rafaelstz** [comment]
Obrigado pelas soluções, usei o seguinte código e parou de aparecer erro, mas fica na tela do print abaixo, estou buscando soluções também para colocar aqui.

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

![image](https://cloud.githubusercontent.com/assets/610598/15519414/c1541882-21d7-11e6-8432-45811aa3a2b0.png)

**Comment by mapaiva** [comment]
Esse é o resultado esperado mesmo. Porque a task `gulp dev` fica observando os arquivos `.sass` para que qualquer modificação feita neles seja convertida em css.
Opa se você encontrar uma solução definitiva para esse problema de arquivos observados seria mt bom kkkk LOL

**Comment by rafaelstz** [comment]
kkkkkk cheguei a pensar nisso mas estava esperando que terminasse no `sass:watch` :yum: Vlw
