### ISSUE TITLE
I install the DEB package, start the display blank

### ISSUE THREAD

**Issue by sikenali** [mapaiva/GitPie#48]
![deepinscreenshot_desktop_20170829162014](https://user-images.githubusercontent.com/26103116/29811443-0dfd8784-8c69-11e7-8613-d521bea20628.png)

**Comment by IonicaBizau** [comment]
Off topic, but what Linux distro/theme is that? :grin:

**Comment by sikenali** [comment]
deepin

**Comment by mapaiva** [comment]
Hello @jingle0927,

Could you please run `gitpie` from the command line and post here the output printed.

In addition, can you provide some specs of your Operating System such as Linux kernel version, distro version and also which version of GitPie you're trying to install?

**Comment by sikenali** [comment]
deepin@deepin:/etc$ uname -a
Linux deepin 4.9.0-deepin11-amd64 #1 SMP PREEMPT Deepin 4.9.40-2 (2017-08-12) x86_64 GNU/Linux

**Comment by sikenali** [comment]
![_desktop_20170921145024](https://user-images.githubusercontent.com/26103116/30682463-508a1132-9edc-11e7-9050-091cdced0e54.gif)
